In [27]:
import pandas as pd
from P6_code.FinishedCode.importData import ImportEV
from P6_code.FinishedCode.dataTransformation import createUsers
import plotly.graph_objects as go

In [28]:
start, end = '2000-01-01', '2022-12-31'

ev_data_caltech = ImportEV().getCaltech(start_date=start, end_date=end, removeUsers=False, userSampleLimit=25)
Users_caltech = createUsers(ev_data_caltech, start, end).data
ev_data_jpl = ImportEV().getJPL(start_date=start, end_date=end, removeUsers=False, userSampleLimit=25)
Users_jpl = createUsers(ev_data_jpl, start, end).data
ev_data_office = ImportEV().getOffice(start_date=start, end_date=end, removeUsers=False, userSampleLimit=25)
Users_office = createUsers(ev_data_office, start, end).data

all_users = pd.concat([ev_data_caltech, ev_data_jpl, ev_data_office], ignore_index=True)
all_users.dropna(subset=['userID'], inplace=True)
all_users.drop(['_id', 'sessionID', 'timezone'], axis='columns', inplace=True)
all_users

clusterID            connectionTime            disconnectTime  \
222        0039 2018-04-30 08:07:49+00:00 2018-04-30 17:27:55+00:00   
583        0039 2018-05-07 07:38:18+00:00 2018-05-07 18:15:01+00:00   
845        0039 2018-05-11 08:17:01+00:00 2018-05-11 17:18:43+00:00   
958        0039 2018-05-14 06:50:26+00:00 2018-05-14 16:09:45+00:00   
1006       0039 2018-05-14 17:06:39+00:00 2018-05-14 18:13:58+00:00   
...         ...                       ...                       ...   
66740      0102 2021-09-09 14:11:44+00:00 2021-09-09 20:47:58+00:00   
66741      0102 2021-09-10 08:33:08+00:00 2021-09-10 16:53:29+00:00   
66742      0102 2021-09-10 14:12:26+00:00 2021-09-10 21:25:47+00:00   
66743      0102 2021-09-13 10:35:32+00:00 2021-09-13 17:26:25+00:00   
66744      0102 2021-09-13 14:21:51+00:00 2021-09-13 20:55:04+00:00   

               doneChargingTime  kWhDelivered siteID spaceID        stationID  \
222   2018-04-30 17:27:51+00:00        47.808   0002  CA-314       2-39-88-24   
583   2018-05-07 18:14:53+00:00        27.683   0002  CA-303      2-39-139-28   
845   2018-05-11 16:05:56+00:00        17.485   0002  CA-314       2-39-88-24   
958   2018-05-14 13:43:40+00:00        11.795   0002  CA-489      2-39-79-380   
1006  2018-05-14 17:39:01+00:00         3.076   0002  CA-303      2-39-139-28   
...                         ...           ...    ...     ...              ...   
66740 2021-09-09 20:47:33+00:00        19.342   0019      08  19-102-260-1640   
66741 2021-09-10 15:49:37+00:00        33.186   0019      03  19-102-260-1634   
66742 2021-09-10 21:25:34+00:00        19.894   0019      08  19-102-260-1640   
66743 2021-09-13 17:26:05+00:00        26.688   0019      03  19-102-260-1634   
66744 2021-09-13 20:54:48+00:00        18.019   0019      08  19-102-260-1640   

          userID                                         userInputs  
222    000000022  [{'WhPerMile': 350, 'kWhRequested': 59.5, 'mil...  
583    000000061  [{'WhPerMile': 400, 'kWhRequested': 8.0, 'mile...  
845    000000022  [{'WhPerMile': 350, 'kWhRequested': 17.5, 'mil...  
958    000000066  [{'WhPerMile': 400, 'kWhRequested': 8.0, 'mile...  
1006   000000061  [{'WhPerMile': 250, 'kWhRequested': 5.0, 'mile...  
...          ...                                                ...  
66740  000006140  [{'WhPerMile': 258, 'kWhRequested': 72.24, 'mi...  
66741  000006620  [{'WhPerMile': 1428, 'kWhRequested': 114.24, '...  
66742  000006140  [{'WhPerMile': 258, 'kWhRequested': 72.24, 'mi...  
66743  000006620  [{'WhPerMile': 1428, 'kWhRequested': 114.24, '...  
66744  000006140  [{'WhPerMile': 258, 'kWhRequested': 72.24, 'mi...  

[48432 rows x 10 columns]

In [4]:
overlapping_users_charging_sessions = all_users[(all_users['userID'].isin(Users_caltech['userID'])) & (all_users['userID'].isin(Users_jpl['userID']))][['userID', 'siteID', 'spaceID', 'connectionTime', 'disconnectTime']]

#Tjek om et tidspunkt er i to intervaller
for i in overlapping_users_charging_sessions.index:
    for j in overlapping_users_charging_sessions.index:
        if i!=j:
            if overlapping_users_charging_sessions['userID'][i] == overlapping_users_charging_sessions['userID'][j]:
                if overlapping_users_charging_sessions['disconnectTime'][i] >= overlapping_users_charging_sessions['connectionTime'][j]:
                    if overlapping_users_charging_sessions['disconnectTime'][j] > overlapping_users_charging_sessions['connectionTime'][i]:
                        print(overlapping_users_charging_sessions.loc[i,])
                        print(overlapping_users_charging_sessions.loc[j,])
                        print('\n')

userID                            000003987
siteID                                 0002
spaceID                              CA-304
connectionTime    2021-07-18 10:34:30+00:00
disconnectTime    2021-07-18 12:12:38+00:00
Name: 30316, dtype: object
userID                            000003987
siteID                                 0001
spaceID                             AG-3F23
connectionTime    2021-07-16 10:52:18+00:00
disconnectTime    2021-07-19 13:41:13+00:00
Name: 63492, dtype: object




KeyboardInterrupt: 

JPL er site 0001 og Caltech er site 0002

Tjek om brugere er både i Caltech og JPL:

In [5]:
Users_caltech['userID'][Users_caltech['userID'].isin(Users_jpl['userID']) & (Users_caltech['userID'].notna())].unique()

array(['000000076', '000000176', '000000340', '000000364', '000000342',
       '000000484', '000000171', '000000396', '000001039', '000000190',
       '000000832', '000000431', '000001011', '000000365', '000000362',
       '000000724', '000000336', '000000448', '000000423', '000001346',
       '000000433', '000001236', '000000420', '000000438', '000000313',
       '000001626', '000000630', '000001564', '000000376', '000001754',
       '000000444', '000000428', '000000372', '000001864', '000001525',
       '000000347', '000001025', '000000533', '000002183', '000000440',
       '000000828', '000000999', '000001797', '000000350', '000000369',
       '000001055', '000002213', '000000400', '000003176', '000002678',
       '000003222', '000001397', '000002507', '000000525', '000001725',
       '000003271', '000000379', '000003711', '000003233', '000000335',
       '000001162', '000000183', '000000419', '000000358', '000001302',
       '000003556', '000000346', '000000394', '000000393', '0000

In [6]:
len(Users_caltech['userID'][Users_caltech['userID'].isin(Users_jpl['userID']) & (Users_caltech['userID'].notna())].unique())

87

Caltech og Office1:

In [ ]:
Users_caltech[Users_caltech['userID'].isin(Users_office['userID']) & (Users_caltech['userID'].notna())]

JPL og Office1:

In [ ]:
Users_jpl[Users_jpl['userID'].isin(Users_office['userID']) & (Users_jpl['userID'].notna())]

Vi ser, at der kun er gengangere mellem JPL og Caltech og fokuserer derfor på disse:

In [57]:
overlapping_sessions = all_users.loc[[30316, 63492, 59076, 59078, 63540, 63550, 63564, 63566], ].sort_values(by='connectionTime').drop(['clusterID', 'stationID', 'siteID'], axis=1)
overlapping_sessions

connectionTime            disconnectTime  \
59076 2020-12-16 13:52:32+00:00 2020-12-16 14:52:07+00:00   
59078 2020-12-16 14:34:39+00:00 2020-12-16 16:23:33+00:00   
63492 2021-07-16 10:52:18+00:00 2021-07-19 13:41:13+00:00   
30316 2021-07-18 10:34:30+00:00 2021-07-18 12:12:38+00:00   
63540 2021-07-21 08:17:47+00:00 2021-07-22 07:36:24+00:00   
63550 2021-07-21 08:27:24+00:00 2021-07-22 07:35:54+00:00   
63564 2021-07-21 09:22:11+00:00 2021-07-22 07:35:55+00:00   
63566 2021-07-21 09:25:07+00:00 2021-07-22 07:35:56+00:00   

               doneChargingTime  kWhDelivered  spaceID     userID  \
59076 2020-12-16 14:31:26+00:00      1.760849  AG-4F43  000001236   
59078 2020-12-16 16:23:16+00:00      5.123000  AG-4F47  000001236   
63492 2021-07-19 13:41:07+00:00      8.180000  AG-3F23  000003987   
30316 2021-07-18 11:44:42+00:00      7.971000   CA-304  000003987   
63540 2021-07-21 09:18:15+00:00      8.047000  AG-1F02  000000169   
63550 2021-07-21 09:15:08+00:00      1.575000  AG-1F04  000000169   
63564 2021-07-21 09:51:15+00:00      1.506000  AG-3F24  000000419   
63566 2021-07-21 09:51:14+00:00      2.563000  AG-3F26  000000419   

                                              userInputs  
59076  [{'WhPerMile': 350, 'kWhRequested': 14.0, 'mil...  
59078  [{'WhPerMile': 350, 'kWhRequested': 14.0, 'mil...  
63492  [{'WhPerMile': 250, 'kWhRequested': 30.0, 'mil...  
30316  [{'WhPerMile': 250, 'kWhRequested': 30.0, 'mil...  
63540  [{'WhPerMile': 360, 'kWhRequested': 14.4, 'mil...  
63550  [{'WhPerMile': 360, 'kWhRequested': 14.4, 'mil...  
63564  [{'WhPerMile': 299, 'kWhRequested': 23.92, 'mi...  
63566  [{'WhPerMile': 299, 'kWhRequested': 23.92, 'mi...

Ved første par af sessioner (59076, 59078) ser vi, at doneChargingTime for den første session ligger før connectionTime for den anden session. Der kan derfor være tale om, at disconnectTime er blevet registreret forkert.

In [46]:
pd.concat([pd.DataFrame(overlapping_sessions.loc[59076, 'userInputs']), pd.DataFrame(overlapping_sessions.loc[59078, 'userInputs'])])

WhPerMile  kWhRequested  milesRequested  minutesAvailable  \
0        350          14.0              40               480   
0        350          14.0              40               480   
1        350          14.0              40               480   

                      modifiedAt  paymentRequired  \
0  Wed, 16 Dec 2020 20:52:31 GMT             True   
0  Wed, 16 Dec 2020 21:35:51 GMT             True   
1  Wed, 16 Dec 2020 23:23:31 GMT             True   

              requestedDeparture  userID  
0  Thu, 17 Dec 2020 04:52:32 GMT    1236  
0  Thu, 17 Dec 2020 05:34:39 GMT    1236  
1  Thu, 17 Dec 2020 05:34:39 GMT    1236

In [31]:
pd.concat([pd.DataFrame(overlapping_sessions.loc[63492, 'userInputs']), pd.DataFrame(overlapping_sessions.loc[30316, 'userInputs'])])

WhPerMile  kWhRequested  milesRequested  minutesAvailable  \
0        250          30.0             120               346   
0        250          30.0             120               346   

                      modifiedAt  paymentRequired  \
0  Fri, 16 Jul 2021 17:52:18 GMT             True   
0  Sun, 18 Jul 2021 17:34:30 GMT             True   

              requestedDeparture  userID  
0  Fri, 16 Jul 2021 23:38:18 GMT    3987  
0  Sun, 18 Jul 2021 23:20:30 GMT    3987

In [53]:
pd.concat([pd.DataFrame(overlapping_sessions.loc[63540, 'userInputs']), pd.DataFrame(overlapping_sessions.loc[63550, 'userInputs'])])

WhPerMile  kWhRequested  milesRequested  minutesAvailable  \
0        360          14.4              40               480   
0        360          14.4              40               480   

                      modifiedAt  paymentRequired  \
0  Wed, 21 Jul 2021 15:17:46 GMT             True   
0  Thu, 22 Jul 2021 12:22:32 GMT             True   

              requestedDeparture  userID  
0  Wed, 21 Jul 2021 23:17:47 GMT     169  
0  Wed, 21 Jul 2021 23:27:24 GMT     169

In [33]:
pd.concat([pd.DataFrame(overlapping_sessions.loc[63564, 'userInputs']), pd.DataFrame(overlapping_sessions.loc[63566, 'userInputs'])])

WhPerMile  kWhRequested  milesRequested  minutesAvailable  \
0        299         23.92              80               360   
0        299         23.92              80               360   

                      modifiedAt  paymentRequired  \
0  Thu, 22 Jul 2021 13:23:46 GMT             True   
0  Wed, 21 Jul 2021 16:25:06 GMT             True   

              requestedDeparture  userID  
0  Wed, 21 Jul 2021 22:22:11 GMT     419  
0  Wed, 21 Jul 2021 22:25:07 GMT     419

In [69]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=[overlapping_sessions.loc[59076, 'connectionTime'], overlapping_sessions.loc[59076, 'disconnectTime']], y=len(overlapping_sessions)*[0]))
fig.add_trace(go.Scatter(x=[overlapping_sessions.loc[59078, 'connectionTime'], overlapping_sessions.loc[59078, 'disconnectTime']], y=len(overlapping_sessions)*[1]))
fig.show()